### PR TITLE
Revert isNodeExecutable: yes

### PR DESCRIPTION
**Pull request by ikeagold**

### CODE REVIEW

**Comment by druellan** [comment]
Just to point out that on Atom 0.183 and CSSLINT 0.0.11, I need this patch to get it working on Windows 8.1

**Comment by rustamli** [comment]
Guys please merge this one, otherwise it doesn't work on Windows. Had to spend sometime before I figured out that it wasn't working because of `isNodeExecutable`

**Comment by ikeagold** [comment]
@AsaAyers @dhagerty9009 @relekang @k2b6s9j someone pls..

**Comment by k2b6s9j** [comment]
I have no pulling power here. You're looking for @hd-demam probably.

**Comment by k2b6s9j** [comment]
/cc @hd-deman 

Damn GitHub mobile.

**Comment by ikeagold** [comment]
@k2b6s9j thank you :thumbsup:

**Comment by k2b6s9j** [comment]
@ikeagold You're quite welcome.

**Comment by Arcanemagus** [comment]
@hd-deman, @kevinsawicki, @zimme, @pborreli:
Can anyone merge this PR so this plugin works properly without modification?

**Comment by ansballard** [comment]
:+1:

**Comment by corintho** [comment]
After making this change on my local installation, I was able to have it properly running in windows. So, a +1 to the fix. And a thank you for ikeagold for spotting the issue and opening the pull request for all of us.

**Comment by k2b6s9j** [comment]
So the real solution here isn't to revert `isNodeExecutable`, it's for this linter to be rewritten for the new Linter 1.0 API. I'll merge this in for now since so many of you are claiming success but this linter is on my queue for linters which absolutely need a rewrite.

**Comment by k2b6s9j** [comment]
This change has been published in v0.0.14

**Comment by ikeagold** [comment]
@k2b6s9j :) this is must be a best code n text editor in a world!

**Pull request merged**
