### PR TITLE
Get project path correctly

### PR DESCRIPTION
**Pull request by clamey**
As a fix for https://github.com/AtomLinter/linter-csslint/issues/73

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Are you interested in becoming a maintainer for this project btw?

**Comment by Arcanemagus** [comment]
And `git rebase master` so you don't have that merge commit :stuck_out_tongue:.

**Comment by Arcanemagus** [comment]
Btw, I'm writing a PR with a spec that tests this.

**Comment by clamey** [comment]
Cool, thanks - I was just testing out Atom + csslint and hit 'watch' on the root issue on a lark.  I'm not really a user of either - vim is hardwired into my brain but I still eval things as the come along

**Comment by Arcanemagus** [comment]
Closing this in favor of #83, as that has specs that test this. Thanks for taking the time to put this up here even though Atom isn't (yet :stuck_out_tongue:) your primary editor!

You've seen the vim-mode package, right?

**Pull request closed without merging**
